Added always failing deployment inspection

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -14,3 +14,22 @@ jobs:
       - run: flyctl deploy --remote-only --ha=false
         env:
           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
+  inspect-staging:
+    name: Inspect staging deploy
+    runs-on: ubuntu-latest
+    needs: deploy-staging
+    steps:
+      - run: |
+          curl https://api.honeycomb.io/1/query_results/testinprodorlivealie \
+          -X POST \
+          -H "X-Honeycomb-Team: ${{ secrets.HONEYCOMB_API_KEY}}" \
+          -d '{"query_id":"5vQuRshh5wN"}' | yq '.id | "QUERY_RESULT_ID="+.' >> "$GITHUB_ENV"
+      - run: |
+          curl https://api.honeycomb.io/1/query_results/testinprodorlivealie/${QUERY_RESULT_ID} \
+          -X GET \
+          -H "X-Honeycomb-Team: ${{ secrets.HONEYCOMB_API_KEY}}" | yq '.data.results.data.COUNT | "FAILURE_REQUEST_COUNT="+.' >> "$GITHUB_ENV"
+      - name: Failure inspection (zero tolerance)
+        if: ${{ FAILURE_REQUEST_COUNT }} > 0
+        run: |
+            echo "::error success_request_count=${{ SUCCESS_REQUEST_COUNT }}::{message}"
+            exit 1
